### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by rutaihwa** [hapijs/hapijs.com#115]
Hello,
Trying to run hapijs.com, after npm install and make I get this response when visiting / 

401
{ message: 'Bad credentials',
  documentation_url: 'https://developer.github.com/v3' }

**Comment by nlf** [comment]
This is intentional, you need to retrieve your own api key from github and edit the `dev_config.json` file and put it there. The README should be updated to reflect this though.

**Comment by nlf** [comment]
Closed via 253b077158491010e922eea6f34ffd9831690244

**Comment by rutaihwa** [comment]
Thanks
