### ISSUE TITLE
Best practices for structuring a Hapi rest api server

### ISSUE THREAD

**Issue by sfabriece** [hapijs/hapijs.com#116]
Hi,
I've been looking for examples of Hapi projects that demonstrate how to structure an an rest api service.
By structure, I mean where to put different components of the app. To make it easier to test and extend.

Any help here would be appreciated.

**Comment by jaw187** [comment]
You'll want to check out the code in https://github.com/hueniverse/postmile-api

Here is a recent blog post which might be helpful as well http://rafaelcorral.com/blog/building-a-restful-api-in-node-using-hapi-js-8

**Comment by sfabriece** [comment]
Thanks :)

**Comment by sandokandias** [comment]
:+1:
