### ISSUE TITLE
List of useful gists

### ISSUE THREAD

**Issue by jardakotesovec** [hapijs/hapijs.com#119]
Recently I came across few very useful gists, like using bell with auth-cookie together, using socket.io with auth-cookie. How about make new section on website where these examples could live similarly as plugins?

Gists have also star rating, that could be displayed via https://github.com/mdo/github-buttons .

Thoughts?

**Comment by nlf** [comment]
I had the thought a while back of changing the 'Tutorials' nav link to 'Learn' and also having code snippets available, which I think is almost exactly what you're talking about here.

**Comment by devinivy** [comment]
This would be great.  A huge benefit I see is that the code examples could demonstrate use of community plugins, whereas the tutorials sections is generally just for vanilla hapi code.

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by nlf** [comment]
resources section has been added
