### ISSUE TITLE
Helper Tutorial

### ISSUE THREAD

**Issue by manonthemat** [hapijs/hapijs.com#131]
I just browsed the website and I kinda missed a tutorial on helper methods. It doesn't have to be its own page, maybe as a subsection for the views page.

What would be a good example to include in the documentation?

**Comment by nlf** [comment]
Do you mean view helpers? Or server methods? Server "helpers" were deprecated some time ago in favor of server methods, which do have a tutorial. View helpers aren't covered though, and would be a great addition in a pull request.

**Comment by manonthemat** [comment]
Good question! I should have been more clear.
I do mean view helpers. What do you think would be a good example?

**Comment by nlf** [comment]
I'm not sure, honestly. I've never used view helpers myself..

Would probably be simplest to add it on to the views tutorial that already exists, and just make up a simple helper that does something very simple and clear to show how it all ties together.

**Comment by manonthemat** [comment]
I think I know what I'm going to write. I shall send a pull request within the next 24h.

**Comment by manonthemat** [comment]
pull request https://github.com/hapijs/hapijs.com/pull/137 for a view helpers tutorial. Example is a random "fortune".
