### ISSUE TITLE
hapi days videos

### ISSUE THREAD

**Issue by jardakotesovec** [hapijs/hapijs.com#140]
There should be link for hapi day videos somewhere on hapijs.com, probably in help section?

**Comment by nlf** [comment]
do we have links for these? would be a great fit for the new resources section

**Comment by AdriVanHoudt** [comment]
https://www.youtube.com/watch?v=x7nq3Q0xrEI&list=PLzc1AUDlJ7WvcMnv3NaEwgh0i2nJKl0GX ?

**Comment by FalloutX** [comment]
Yaa. Adding some Vidoes on HapiJS would be great. I do want to add some videos that I watched while I started doing hapi.

**Comment by nlf** [comment]
closed via #204
