### ISSUE TITLE
api filtering in code or db

### ISSUE THREAD

**Issue by sfabriece** [hapijs/hapijs.com#143]
I'm implementing a Rest Api and i'm wondering where filtering should happen. In code: by returning the Whole Object and the filtering or by filtering in sql? 
Thanks for the help.

**Comment by AdriVanHoudt** [comment]
I think it would better to ask this 
* in https://gitter.im/hapijs/hapi (prefered)
* or here https://github.com/hapijs/discuss

Either way depends on the structure of your code. Perf wise I think sql would be faster but not sure.
