### ISSUE TITLE
Auth0 using Hapi

### ISSUE THREAD

**Issue by dschenkelman** [hapijs/hapijs.com#149]
This is the information requested:
* **Company name**: Auth0
* **Use case**: v2 of our API (v1 used express)
* **Environment**: Production (https://docs.auth0.com/apiv2)
* **Contact information**: damian@auth0.com
* **Link to logo**: https://cloudup.com/cmshMvKt2bD
* **User quote**: "hapi's clear structure, in particular its plugin system and request lifecycle, makes it easy for us to separate cutting concerns from our API business logic allowing us to add features and fix bugs at a fast pace." **Attribution**: Damian Schenkelman, Engineer at Auth0.

Please let us know if you need anything else.

**Comment by dschenkelman** [comment]
That was fast, thanks!

**Comment by nlf** [comment]
:) Thank you!

**Comment by dschenkelman** [comment]
That was fast, thanks!
