### ISSUE TITLE
Add mullet to the plugins/boilerplate section

### ISSUE THREAD

**Issue by olhapi** [hapijs/hapijs.com#159]
Hello there. Maybe you can add this boilerplate to plugins section?
https://github.com/lynnaloo/mullet

**Comment by lloydbenson** [comment]
Not sure how you liked what I did for the description but this is how you would do that PR.

**Comment by olhapi** [comment]
Thanks. Now I know what to do next time.

**Comment by lloydbenson** [comment]
I saw you closed this.  Is the description fine or do you prefer something else?  If the description is fine then we can merge in the PR.

**Comment by olhapi** [comment]
Everything ok. Just want to add this boilerplate to plugins list.
