### ISSUE TITLE
getting-started no longer correct?

### ISSUE THREAD

**Issue by goofballLogic** [hapijs/hapijs.com#168]
The breaking change in good which should have been fixed by pull request "Update good-console example #164" only prevents start-up error. Functionality of the getting-started (logging) tutorial appears to still be broken.

#### Symptoms
Tutorial says
````
And if we visit http://localhost:3000/ in the browser, you'll see:

140625/143205.774, request, http://localhost:3000: get / {} 200 (10ms)
````

but this log never appears.

#### Initial analysis
1. hapi seems to now propagate "request" events as "request-internal"
2. good appears not to propagate "request-internal" to reporters. I may misunderstand the code...

#### Context
Windows 7
node 0.12
hapi 8.4.0
good 6.1.0
good-console 5.0.0

**Comment by AdriVanHoudt** [comment]
as you can see in the diff https://github.com/hapijs/hapijs.com/pull/164/files the response even got switched out and request added. Add `response: '*'` to the events and it should work.
