### ISSUE TITLE
Boilerplates

### ISSUE THREAD

**Issue by arb** [hapijs/hapijs.com#185]
It might be worth adding a section somewhere to list hapi boiler plates that are available.

**Comment by gergoerdosi** [comment]
The list is here: http://hapijs.com/plugins#Boilerplate. Or you mean to add it somewhere else?

**Comment by arb** [comment]
I don't think it really belongs under plugins. Full disclosure I didn't even look at plugins because it doesn't make sense to me for it to be there.

**Comment by gergoerdosi** [comment]
I agree. I think "Resources" would be a better place, we already have a "Gists and code samples" section.

**Comment by nlf** [comment]
moving it to resources makes sense to me

**Comment by AdriVanHoudt** [comment]
:+1: makes sense to me
