### ISSUE TITLE
Add plugin docs to API section

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapijs.com#196]
In 9.x, many of the built-in features are moving out and will require loading the plugins directly. This will include **inert** (file and directory handlers), **vision** (view templates), and **h2o2** (proxy). When this happens, the API section of the site will become less useful as those sections of the api document in **hapi** will be removed.

I'd like to see the API section updated to include other plugins alongside hapi core. I know @geek is adding a new `/module/lab` area to the site so that might be one way.

One idea is to simply have an `API.md` file in each plugin and just use that the same way.

**Comment by JustinBeaudry** [comment]
https://hapijs.com/api#plugins has not updated with this request. Is this still something worth pursuing? Seems like a worthwhile endeavor, but don't want to jump on this without having some confirmation of desire.

**Comment by hueniverse** [comment]
We did move most modules to use their own API.md file. We still need to enhance the API "reader" to be able to not only render the core hapi api doc, but also all of the modules with API.md file. That would be really great.

**Comment by hueniverse** [comment]
There is another issue for adding the missing docs.
