### ISSUE TITLE
Does a detailed example Chat app using Hapi.js, Socket.io & Redis qualify as a "Resource"?

### ISSUE THREAD

**Issue by nelsonic** [hapijs/hapijs.com#198]
Hi, we made this example app: https://github.com/dwyl/hapi-socketio-redis-chat-example and are wondering if it qualifies for a inclusion in the resources of hapijs.com ...
http://hapijs.com/resources ??
Thanks!

**Comment by nlf** [comment]
I would say it absolutely qualifies

**Comment by nelsonic** [comment]
Thanks for confirming @nlf  (_hope you are well!)
@iteles can you please prepare the PR? :+1:

**Comment by iteles** [comment]
Wonderful, will do! :blush:

**Comment by sericaia** [comment]
:+1:

**Comment by nlf** [comment]
closed via #201

**Comment by iteles** [comment]
Thanks @nlf, we really appreciate it! :tada:
