### ISSUE TITLE
#swag

### ISSUE THREAD

**Issue by dypsilon** [hapijs/hapijs.com#2]
The #hapi channel on freenode demands a way to buy t-shirts and stickers with Hapi logos!

**Comment by manonthemat** [comment]
+1 for swag

**Comment by minustime** [comment]
+1

**Comment by AdriVanHoudt** [comment]
:+1: for stickers

**Comment by briandela** [comment]
Would love to buy a t-shirt if they are available.

**Comment by briandela** [comment]
and also :+1: for stickers

**Comment by hueniverse** [comment]
The marks are all under BSD. You are free to create any short designs you want with the logos and make them available via the many online stores that do these kinds of things... There is no one else to produce these at this point. There is no company running this project. It's just us, the community. If you want to see this happens, do it.

**Comment by arb** [comment]
Are the logos hosted anywhere in a high enough quality to put on wearables and stickers?

**Comment by gergoerdosi** [comment]
There is a large version of the hapi logo here: https://raw.githubusercontent.com/hapijs/hapi/master/test/file/image.jpg

**Comment by nlf** [comment]
this one's an svg so should be good for resizability and whatnot http://hapijs.com/public/img/logo.svg

**Comment by danielb2** [comment]
unixstickers.com  is  a place for nice stickers btw. I'd like to see a hapi sticker there myself

**Comment by nvcexploder** [comment]
I got the original ones at sticker mule. I could just duplicate the order of folks want

**Comment by maxbeatty** [comment]
@nvcexploder maybe you could list that original one on [Sticker Mule's Marketplace](https://www.stickermule.com/marketplace) so people can order as they like? I could try to create a new sticker and list it here if that's easier

**Comment by nvcexploder** [comment]
Sure thing! I'll do that as soon as I'm near a computer.

**Comment by hueniverse** [comment]
@nvcexploder so this comment above was delivered via carrier pigeon?

**Comment by nlf** [comment]
Ben has the best carrier pigeons in the business

**Comment by AdriVanHoudt** [comment]
some stickers are gold on there https://www.stickermule.com/marketplace/1580-move-slow-and-make-things

**Comment by danielb2** [comment]
To vote for the hapi stickets on unixstickers.com go here: https://trello.com/c/5iLadkxD/153-hapi-js-stickers

it just got added as an option to vote for

**Comment by nvcexploder** [comment]
https://www.stickermule.com/marketplace/8560-hapi-dot-js-helmet

These should be available now - sorry it took me so long!

**Comment by manonthemat** [comment]
Nice sticker! :+1:

**Comment by AdriVanHoudt** [comment]
Ordered :tada:

**Comment by nvcexploder** [comment]
Rad!!!

**Comment by cgiacomi** [comment]
:+1:

**Comment by JustinBeaudry** [comment]
Is there an update on putting swag on the hapijs site? Maybe it should just be a shopify store with a link from the hapijs site? @nvcexploder?

**Comment by hueniverse** [comment]
We are not really in the business of selling stuff. It does not belong on the site.
