### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by kevinsimper** [hapijs/hapijs.com#202]
When you go to http://hapijs.com/api#replyproxyoptions there is a broken link

```
http://hapijs.com/api#route.config.proxy
```

**Comment by gergoerdosi** [comment]
Looks like this is an issue with the site. It works on GitHub: https://github.com/hapijs/hapi/blob/master/API.md#route.config.proxy

**Comment by maxbeatty** [comment]
Is this still valid w/ the v9 release? I'm having trouble reproducing

**Comment by nlf** [comment]
proxy support was removed from core, so this is no longer valid
