### ISSUE TITLE
8.8.1 API docs are down

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapijs.com#213]
Seeing a string of numbers rather than the API documentation.  http://hapijs.com/api/8.8.1 is broken but http://hapijs.com/api/8.8.0 is fine.  I'm running latest Chrome.  I don't see any failed requests or JS errors in my console.  Curious!

**Comment by nlf** [comment]
confirmed bug, working on it now.

**Comment by nlf** [comment]
closed via 89f5af30f31988ada986c90dee8bbae3cdb8d85b
