### ISSUE TITLE
Can't click on some footer links

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapijs.com#215]
The "Twitter" and "Need Help" links in the footer can't be clicked because the fixed position sidebar overlaps them. Think a `position:relative` on the footer should fix it.

![screen shot 2015-08-01 at 15 11 23](https://cloud.githubusercontent.com/assets/916064/9022117/9b4e7a36-385f-11e5-8322-e1e859e1d41d.png)

**Comment by joshvoll** [comment]
let me fix this for you @mtharrison
