### ISSUE TITLE
"Lint" the tutorials

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapijs.com#217]
I think it would be worthwhile to ensure that all the tutorials abide by the hapi style guide.  I see some minor lapses, such as missing new lines at the top of function definitions.  Might feel nice for it to be totally consistent :)

Anyone know if there's a way we can leverage lab to lint the inline code examples?

**Comment by mtharrison** [comment]
Read my mind :+1:  was just going to submit this issue

**Comment by devinivy** [comment]
It's a little loosey-goosey right now, but I have something that to look at.  It's linting "js"/"javascript" fenced code blocks within the markdown files via lab with correct line numbers:
```
Linting results:
	lib/tutorials/auth.md:
		Line 26: hapi/hapi-scope-start - Missing blank line at beginning of function.
		Line 32: hapi/hapi-scope-start - Missing blank line at beginning of function.
		Line 37: hapi/hapi-scope-start - Missing blank line at beginning of function.
		Line 44: hapi/hapi-scope-start - Missing blank line at beginning of function.
		Line 50: hapi/hapi-scope-start - Missing blank line at beginning of function.
...
```

We'll have to account for partial code examples somehow– it's common to run into parse errors since code examples aren't always proper javascript.  Someone has made some ground transforming code examples into valid javascript in a separate project: https://github.com/ChrisWren/mdlint/blob/master/index.js#L352-L381.

If you want to try it, checkout the [lint-tutorials](https://github.com/devinivy/hapijs.com/tree/lint-tutorials) branch on my fork, `npm install`, then `npm run lint:tutorials`.

**Comment by nlf** [comment]
So originally the tutorials all followed the style guide, but Eran and I decided the whitespace was a bit much for viewing purposes. Everything else should follow the guide though

**Comment by devinivy** [comment]
Should it be two spaces?  Three?  I saw some examples with three spaces.  We can override the hapijs lint rules specifically for markdown files within this repo– we just need to decide on the rule exceptions.

**Comment by hueniverse** [comment]
I would apply the style guide except the empty lines rule

**Comment by devinivy** [comment]
I'd like to revive this.  @hueniverse can you be more specific about the eslint or style guide rule you're referring to?  There are several that deal with empty lines.

Do we feel good about using four space indents in the tutorials?  I'm personally partial to that rule respecting the style guide.

**Comment by hueniverse** [comment]
I think code in documentations is not the same as code in, well, code. I would minimize empty lines. I only use 4 spaces so I would just do that here too unless we are talking about some crazy nested callbacks.

**Comment by nlf** [comment]
yeah honestly i think the only rule we need to ignore is the empty lines rule. if we have tutorials that are nesting callbacks far enough for four spaces to be a problem then we should probably rewrite the tutorial's code IMO

**Comment by devinivy** [comment]
As far as eslint goes, are you both referring to `hapi-scope-start`?

**Comment by nlf** [comment]
yeah i think that's probably the only rule we care about ignoring

**Comment by devinivy** [comment]
Pending PR: #240
