### ISSUE TITLE
Updates page shows milestones in incorrect order

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapijs.com#221]
Milestone 9.0.0 is lower down on the page than 8.8.1 because it has a lower ID number (it was created before). I will address this in a separate PR by using the node semver module to sort the milestones.

![screen shot 2015-08-12 at 08 57 31](https://cloud.githubusercontent.com/assets/916064/9219100/4d40a480-40d0-11e5-8db3-21b9e058da23.png)

**Comment by AdriVanHoudt** [comment]
ow lol did not even see that, disregard my other comment on 9.0 not being included yet :P
