### ISSUE TITLE
Add a cookbook section

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapijs.com#226]
We need a simple "how do I ____?" section where we cover all the common questions.

**Comment by AdriVanHoudt** [comment]
Any samples to start working with?

**Comment by hueniverse** [comment]
- how to serve a file?
- how to serve a directory?
- how to proxy to another server?
- how to render a view with a template language?
- how to set up a cookie-based session?

etc.

**Comment by hueniverse** [comment]
Think of it as stackoverflow style Q&A but edited.

**Comment by AdriVanHoudt** [comment]
ah like that

**Comment by sirgallifrey** [comment]
I would like to help with that, but how this cookbook section would be different from the tutorials? It would be more specific? More didactic?

**Comment by hueniverse** [comment]
Tutorials seems good enough.
