### ISSUE TITLE
Link release notes

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapijs.com#231]
It seems for some people (espacially newcomers) it is hard to find the release note. The new updates helps but does not include the actual release note.
Would it be possible to link the issue with the matching milestone and `release notes` label to the milestones on the /updates page?

**Comment by AdriVanHoudt** [comment]
see https://github.com/hapijs/hapi/issues/2682#issuecomment-130557398

**Comment by Marsup** [comment]
Let's ignore "release notes" in the changelog and put it next to the version number ?

**Comment by AdriVanHoudt** [comment]
I think matching on milestone + tag is more reliable than title no?

**Comment by Marsup** [comment]
I wasn't talking about text matching, gh labels.

**Comment by AdriVanHoudt** [comment]
ah yes than we are on the same page, i think :D

**Comment by nlf** [comment]
generally we only have release notes for major releases, so for minor and patch releases what would we display instead?

**Comment by AdriVanHoudt** [comment]
for patches it is usually 1 or 2 issues/PR's, I think that is manageable to read themselves no?

**Comment by nlf** [comment]
sure. i think we could keep the current layout and just add a "release notes" link next to versions that have an associated release notes issue.

**Comment by AdriVanHoudt** [comment]
added to my `when I have free time` list ;)
