### ISSUE TITLE
Document hapi version on tutorials

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapijs.com#233]
Please add a version number to each tutorial showing on hapijs.com. This way people will stop failing to use newer versions of hapi before we get to update all the documentation on the site.

**Comment by AdriVanHoudt** [comment]
I get where this is coming from but with the same effort you could also just update the docs :P

**Comment by hueniverse** [comment]
Until the next breaking changes. How about whoever has the time to update the docs does both...

**Comment by AdriVanHoudt** [comment]
Also an option, how would this work though? Mark unupdated docs? But soms don't need it, might lead to confusion and if you have to over the docs to mark the ones that need updating you might as well update them no?

**Comment by hueniverse** [comment]
If the tutorial just said "Up to date as of hapi v8.5.x", it will give people an idea of what might be wrong if it doesn't work for them.

**Comment by nlf** [comment]
closed via #234
