### ISSUE TITLE
Compatiblity with hapi 10

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/hapijs.com#254]
Many of the tutorials have this line: "*This tutorial is compatible with hapi v9.x.x.*". I assume all these tutorials are also compatible with hapi 10. Should we just bump the version and use "*This tutorial is compatible with hapi v10.x.x.*" or both versions should be shown like "*This tutorial is compatible with hapi v9.x.x and v10.x.x.*"?

**Comment by devinivy** [comment]
Good point.  I think it should say whatever is most broadly true.  So if it's fine for hapi v9 and hapi v10, then that's what it should claim.

**Comment by AdriVanHoudt** [comment]
yeah just needs a bump since 10 and 9 are the same, the lts branch will have the docs compatible for lts(9 atm), maybe we can make a page on the website with the lts docs once they start being different

**Comment by nlf** [comment]
for tutorials, we should keep them up to date with the latest release only (in this case, 10.x). if they happen to be compatible with older versions too, neat. if not, oh well.

i don't want to get into a tangle of having to list every version a tutorial is compatible with. the tutorials and site in general should be focused primarily on supporting the latest versions.

**Comment by nlf** [comment]
keeping this open until we update all the headers in the tutorials
