### ISSUE TITLE
Links on right side are not scrollable

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/hapijs.com#256]
The right side of the page contains links to sections, but it's not possible to scroll down there.

http://hapijs.com/api#server

<img width="1280" alt="screen shot 2015-09-13 at 20 40 51" src="https://cloud.githubusercontent.com/assets/371149/9838216/f9a7e68e-5a57-11e5-9145-80febb3d73fa.png">

**Comment by nlf** [comment]
for me the link section can be scrolled independently from the main content, is that not the case for you? what happens if you hover your mouse over the nav section and try to scroll there? i agree we need to come up with a better fix for the nav issues here..

**Comment by devinivy** [comment]
I experience this too on Chrome 45.  If the API navigation is expanded beyond the height of the window, then there's nothing you can do to see the those items overflowing the window.

**Comment by AdriVanHoudt** [comment]
Somehow `column nav-secondary` has `height` and `min-height` that updates as you scroll. When turned off I can scroll but the moment I scroll with the main element(the api text div) it updates again and disables scrolling.

**Comment by HenrikJoreteg** [comment]
I was just about to go file the same bug, I hit this too in Chrome Version 45.0.2454.85

**Comment by nlf** [comment]
i just deployed some changes to the nav layout, does that solve this problem for those that reported it? @gergoerdosi @devinivy @HenrikJoreteg

**Comment by gergoerdosi** [comment]
Yes, it works now! Thanks.

**Comment by devinivy** [comment]
:+1: fixed!
