### ISSUE TITLE
Getting Started could ramp up slowly with more narrative

### ISSUE THREAD

**Issue by strand** [hapijs/hapijs.com#264]
I was reading over the [getting started](http://hapijs.com/tutorials/getting-started) guide last night and was surprised when the guide jumped from routes to using a plugin for logging. I am completely new to Hapi, and I expected there to be some progression like (strikethrough indicates we have content for this):
- ~~hello world~~
- ~~displaying a static page~~
- displaying a dynamic page (based on route)
- implementing app reloading in development
- adding a persistence layer
- displaying a dynamic page (based on persistence)
- adding logging
- ~~other plugins~~

Would the Hapi team be amenable to this sort of documentation improvement? I'd be glad to write documentation to ensure that new-comers can more easily dive in.

**Comment by lloydbenson** [comment]
I suspect folks would be most welcome to any ideas here on improvement.  Maybe do a PR with a brief outline for feedback?

**Comment by strand** [comment]
I suspect this will be several PRs, so I'll see if I can write a section about displaying a static page in the next day or two.

**Comment by nlf** [comment]
That sounds like a perfect approach :)

**Comment by strand** [comment]
@hueniverse, thanks for closing. Obviously, this fell off my plate.
