### ISSUE TITLE
Repo images

### ISSUE THREAD

**Issue by TrySound** [hapijs/hapijs.com#269]
Please, move useless images from repos (and npm modules) to your site or some image cdn. Nobody want to load them in every package. Okay, your repos and modules should be deepEqual, but please try to make both more simple and small. It's not too difficult, it's not too long.

**Comment by nlf** [comment]
I think you may have opened this issue on the wrong repo. Try at https://github.com/hapijs/discuss

**Comment by hueniverse** [comment]
I think there are nicer ways of saying that too.
