### ISSUE TITLE
LICENSE for hapijs.com repository?

### ISSUE THREAD

**Issue by jmdobry** [hapijs/hapijs.com#276]
I'd like to submit a documentation update pull request, but per company policy I can't unless this repo has a LICENSE file that spells out, well, the license. Any chance of getting one added? I can submit a PR that adds the same LICENSE file that's in the hapijs repo if that's okay.

**Comment by AdriVanHoudt** [comment]
you can find the license here: https://github.com/hapijs/hapijs.com/blob/master/package.json#L30

**Comment by jmdobry** [comment]
Yep I saw that, but unfortunately they're requiring that there be an actual license file in this repository in order for me to contribute.

**Comment by AdriVanHoudt** [comment]
ok weird policy so are you allowed to do a PR to add the license since technically there is no license yet at that point?

**Comment by jmdobry** [comment]
Yes
