### ISSUE TITLE
Tighten up plugins page whitespace

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapijs.com#285]
The plugins page is getting pretty scroll-tastic. Wonder if reducing some of the whitespace between plugins would make it a bit of a better experience?

![screen shot 2015-10-30 at 22 44 03](https://cloud.githubusercontent.com/assets/916064/10859698/e1cde610-7f57-11e5-979a-be784d0f0ab6.png)

**Comment by AdriVanHoudt** [comment]
:+1:
