### ISSUE TITLE
Link to breaking changes

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapijs.com#306]
Following a discussion on gitter, it seems we're doing a bad job at showing breaking changes for users not following closely the project or upgrading from old versions.

We could either link to the release notes on github or parse them to show it on the websites, what do you think ? Other ideas ?

**Comment by hueniverse** [comment]
Sounds like a good idea.

**Comment by AdriVanHoudt** [comment]
The release notes are on the updates page but maybe make them more visible and link to the updates page from the readme?

**Comment by Marsup** [comment]
They are, but spread over several pages. Imagine having to go from 8 to 11 without knowing how we use labels in the org, not that easy.

**Comment by AdriVanHoudt** [comment]
hmm true, maybe link to major releases on the left (a menu like on /api) with links to the release notes?

**Comment by nlf** [comment]
yeah, i think a small "release notes" section above the full changelog on the updates page would make sense

**Comment by devinivy** [comment]
Although I send people to the website and like to think that the website is the clear go-to for hapijs information, I think we might need to be more overt/explicit in the readme about where to find certain crucial information.  I imagine people will putz around github for ages (not understanding our system) before going to the site.  Most framework sites aren't as extensive as hapijs.com.

**Comment by SanderElias** [comment]
HI, I was the one raising the issue. 
@AdriVanHoudt, That would be a good place. Also a remark that the breaking changes are (very well) documented in there would help some people.

**Comment by AdriVanHoudt** [comment]
I saw something pass by on Bitter :P how would you place that remark?

**Comment by SanderElias** [comment]
@AdriVanHoudt:  "Major versions Release notes including breaking changes"?

**Comment by AdriVanHoudt** [comment]
seems like this is still an issue https://github.com/hapijs/hapi/issues/3241

**Comment by hulbert** [comment]
Somewhat related to this (can open a new issue if appropriate) `14.0.0` [shows](http://hapijs.com/updates) "Release notes" next to it but `15.0.0` does not, despite [this issue existing](https://github.com/hapijs/hapi/issues/3323).
