### ISSUE TITLE
changelog only shows changelog for other hapi repos from closed milestones 

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapijs.com#316]
see https://github.com/hapijs/hapijs.com/blob/master/lib/changelog.js#L29
this causes the 'sub changelog' to not show when the maintainer forgets to close the milestone
current example in 12.x milestone ![](http://puu.sh/mkeok/9bef25cfb0.png)

2 solutions:
- leave like is and open issues on the repos where the milestone is not closed
- remove the requirement and be looser and show the changelog anyway

**Comment by nlf** [comment]
yeah.. we could probably change this to show sub changelogs even if the milestone is still open, though plugin maintainers should probably be closing their milestones :)

**Comment by AdriVanHoudt** [comment]
we could also show not closed milestones and show it somehow in the changelog?

**Comment by AdriVanHoudt** [comment]
@nlf you want a PR to also show non closed and maybe show it somehow in the UI?
