### ISSUE TITLE
npm start?

### ISSUE THREAD

**Issue by tomleo** [hapijs/hapijs.com#317]
In `getting_started` tutorial there is the following paragraph

```
Start up your server with npm start and go to http://localhost:3000/hello in your browser. 
Oh no! We're getting a 404 error because we never created a hello.html file. 
You need to create the missing file to get rid of this error.
```

When I enter `npm start` in the command line I get the following

```
npm ERR! Linux 4.2.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tom/hacking/learnjs/npm-debug.log
```

The homepage recommends "Launch the application by running `node .`" which works for me. So I'm confused about the alternate way to start the application via the node package manager.

**Comment by Marsup** [comment]
LGTM : https://github.com/hapijs/hapijs.com/blob/master/package.json#L22

**Comment by gergoerdosi** [comment]
Have you saved the file as `server.js`?

**Comment by nlf** [comment]
yeah, if the instructions are followed you would save the file as `server.js`, and `node server` happens to be npm's default start script if one is not specified, so it should just work.

**Comment by tomleo** [comment]
Ahh my mistake (still learning js), The `npm init` utility has a default "entry point" of `index.js`. The home page also says:

```
Create an index.js file with the following contents
```

so that was the file I created. Moving that file to `server.js` makes `npm start` work. I think the home page should suggest creating a file called `server.js` instead of `index.js` to avoid confusion if a person then jumps into the tutorial.

**Comment by nlf** [comment]
I agree :) we'll get that changed

**Comment by Marsup** [comment]
I don't get it, there's already a server.js, start script runs it, am I missing something ?

**Comment by nlf** [comment]
He's talking about the guide on the front page, it's inconsistent with the getting started tutorial
