### ISSUE TITLE
Is there anyway to unescape query parameter for every request

### ISSUE THREAD

**Issue by noppanit** [hapijs/hapijs.com#329]
Right now we're unescaping in the route but just wondering if hapi has some kind of a filter before it goes to the route so I can just do it in one place? 

This is what I'm doing right now. 

```
var querystring = require('querystring');

function dateToString(date) {
  return moment(new Date(querystring.unescape(date))).toISOString();
}
```

**Comment by jaw187** [comment]
Have you looked into Joi validation?

**Comment by noppanit** [comment]
We're using Joi but not sure if Joi can automatically do that?

**Comment by jaw187** [comment]
https://github.com/hapijs/joi/blob/master/API.md#dateiso

**Comment by noppanit** [comment]
I thought that was just validation and not unescaping the query string?

**Comment by hueniverse** [comment]
Please post questions in hapijs./discuss, not here.
