### ISSUE TITLE
Fix directory structure consistency in Views tutorial

### ISSUE THREAD

**Issue by vitorbaptista** [hapijs/hapijs.com#333]
There are a few parts that you use a `templates` base directory, as in the first code block:

```javascript
    server.views({
        engines: {
            html: require('handlebars')
        },
        relativeTo: __dirname,
        path: 'templates'
    });
```

In other parts, you use `views` as a base directory:

```
For example, if you have a directory structure like:

views\
  index.html
  layout\
    layout.html
  helpers\
    getUser.js
    fortune.js
```

Considering that you use `templates` as a base directory in this repository, I would guess that's what you recommend. I'd be happy to send you a pull request if that's the case :+1:

**Comment by nlf** [comment]
feel free to send a pull request for any changes to the tutorials that you see fit :)
