### ISSUE TITLE
Add microapps to ../community

### ISSUE THREAD

**Issue by alexandresaiz** [hapijs/hapijs.com#335]
Company name: **microapps**
Product name or use case: **[MONEI](http://monei.net)**
Is it in production or development? **It's in production**
Contact information for further questions: **hi@mcroapps.com**
Contact information for security alerts **hi@microapps.com**
Link to logo if we can showcase your company on the new site:
http://site-cdn.microapps.com/wp-content/uploads/2015/12/microapps.svg
User quote (with attribution) about your hapi user experience (up to 300 characters): 

> **hapi is a simple yet powerful framework which goes out of your way. @alexandresaiz**

**Comment by jkup** [comment]
I'm looking to get started helping out with Hapi! Are these "add to community" issues ok to be turned into PRs?

**Comment by hueniverse** [comment]
@jkup yep

**Comment by alexandresaiz** [comment]
Thanks for adding our project!

**Comment by nlf** [comment]
closed via #359
