### ISSUE TITLE
Tools/utilities that don't fit as plugins

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapijs.com#339]
I wrote a tool called hapi-runplugin specifically to easily list what endpoints are returned by running a given plugin. When things are organized in different repos and they are re-used and it's not always sensible to test something via a server, this comes in handy.

Regardless, the webpage has a plugins section, but no section for tools. A composer like Glue is a tool like this which also has value.

I've noticed that Glue can easily be overlooked, so this would solve that.

thoughts?

Ref: https://github.com/hapijs/contrib/issues/76

**Comment by Marsup** [comment]
Boilerplates are in the section resources, what would you think about putting tools there too ? Seems similar.

**Comment by danielb2** [comment]
That works. I don't think tools have enough stuff to warrant it's whole own section

**Comment by danielb2** [comment]
I'll just submit a PR to put that in and close this for now.
