### ISSUE TITLE
Consistent use of arrow functions ?

### ISSUE THREAD

**Issue by stefk** [hapijs/hapijs.com#343]
Hi,

I'm just discovering hapijs and I'm little confused by the mix of es6 and es5 styles in anonymous function declarations in the documentation. Is there a reason why, for example, route handlers never use the arrow syntax? It doesn't seem so at first sight, but I may overlook something.

**Comment by mtharrison** [comment]
You probably shouldn't use arrow functions as route handlers. hapi relies on being able to bind `this` to whatever it wants inside a handler (see [`server.bind()`](http://hapijs.com/api#serverbindcontext)). You can't bind `this` for arrow functions. see:

```javascript
// Non-arrow function

const func1 = function () {

    console.log(this.cache['something']);
}

// Arrow function

const func2 = () => {

    console.log(this.cache['something']);
}

const cache = {
    something: 'value'
};

func1.bind({ cache })();    // logs 'value'
func2.bind({ cache })();    // Throws Cannot read property 'something' of undefined
```

**Comment by Marsup** [comment]
I think he refers to snippets on the website so it's probably OK here.

**Comment by stefk** [comment]
I thought it could be a documentation issue, because arrow functions can actually be used in most of the examples. Thanks for the explanation!
