### ISSUE TITLE
Broken link in Plugins section

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapijs.com#346]
The third plugin [hapil18n](https://github.com/gpierret/hapi18n) in the Localization/Internationalization section sends to a 404 and the Github user as well. I guess it should be deleted from the section.

I can submit a PR for it if you want if it has not been done already.

**Comment by Marsup** [comment]
There's his contact info on npm, you could try to contact him 1st see if he moved those projects.

**Comment by Nargonath** [comment]
@marsup Fair enough, I'll do that and let you know where it ends up.

**Comment by Nargonath** [comment]
@marsup Just tried to send an email to the email address linked in his npm account but I got a "Delivery to the following recipient failed permanently". I guess it doesn't exist anymore. Shall I delete its entry in the documentation?

**Comment by Marsup** [comment]
Wow, he really vanished. Let's wait a bit, some github profiles disappeared and came back in the last few days.

**Comment by Nargonath** [comment]
Ok, let's do that.

**Comment by Nargonath** [comment]
@Marsup I just checked and the github profile + repo still pointing to a 404. Should I submit a PR?

**Comment by Marsup** [comment]
Go for it.
