### ISSUE TITLE
Testimonial - GOV.UK

### ISSUE THREAD

**Issue by davidjamesstone** [hapijs/hapijs.com#380]
The [Flood warning service](https://flood-warning-information.service.gov.uk/) site that provides a service to users looking for flood information in the U.K.

This is a very busy service during wet periods and is a flagship site for the Environment Agency.

We have recently moved from Express to hapi - a really great experience.

I wondered if you would like to use our success story in your testimonials?

**Company name:** GOV.UK
**Product name or use case:** Flood warning services
**Is it in production or development?:** Production
**Contact information for further questions:** davidjamesstone@gmail.com
**Contact information for security alerts:** davidjamesstone@gmail.com
**Link to logo if we can showcase your company on the new site:** https://assets.digital.cabinet-office.gov.uk/static/images/gov.uk_logotype_crown-14b98db97bbd6cb1f33935d3e0d973fa68ca0c38fb5762b033423ceffe9e16f6.png
**User quote (with attribution) about your hapi user experience (up to 300 characters):** hapi's configuration centric approach and simple but powerful request model has meant that productivity, quality and satisfaction have vastly improved. We are able to focus our attention to business logic and the code we produce is far more approachable and reasonable. For enterprise level nodejs applications, look no further than hapi.

**Comment by mtharrison** [comment]
Cool!

**Comment by davidjamesstone** [comment]
Thanks!

Here's the [code](https://github.com/EnvironmentAgency/live-flood-warnings) if you're interested.

We now have 3 hapi-based products, one in development and we're banging the drum to get other teams and gov departments on board.

**Comment by Marsup** [comment]
@nlf add him to the security ML ?
