### ISSUE TITLE
Getting Started Tutorial breaking with Good

### ISSUE THREAD

**Issue by sjmcdowall** [hapijs/hapijs.com#382]
Looks like good made a breaking change -- and you get an error now with ops.interval not defined or whatever.. Anyway it looks like we need to have 👍 
    ops: {
        interval: 1000
    },

in the config area now ..

**Comment by lloydbenson** [comment]
I think that is likely a bug @arb?

**Comment by arb** [comment]
Yeah there's an open issue over [here](https://github.com/hapijs/good/issues/487)

**Comment by arb** [comment]
Version 7.0.1 published; this should no longer be a problem.
