### ISSUE TITLE
hapi Community Addition

### ISSUE THREAD

**Issue by jhawlwut** [hapijs/hapijs.com#384]
**Company name**
Liaison Technologies
 
**Product name or use case**
Alloy
 
**Is it in production or development?**
Production

**Link to logo if we can showcase your company on the new site**
https://www.liaison.com/wp-content/uploads/2015/11/logo.png
 
**User quote (with attribution) about your hapi user experience (up to 300 characters)**
“Hapi is integral to our Alloy data management and integration platform. What used to take months in an enterprise-heavy architecture is cut down to weeks, sometimes just hours, and future-proof to meet the demands of our customers.” 
_- Jonny Hawley, Liaison Technologies_

**Comment by hueniverse** [comment]
@jhawlwut this would probably be faster if you submitted a PR to https://github.com/hapijs/hapijs.com/blob/master/lib/community.js

**Comment by nlf** [comment]
closed via #409
