### ISSUE TITLE
'See all' links on Contribute page are broken

### ISSUE THREAD

**Issue by karanjthakkar** [hapijs/hapijs.com#398]
- `See All` link for `Issues for new contributors` points to:

`https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Ahapijs+label%3A%22new+contributor%22+` 
instead of 
`https://github.com/hapijs/hapi/issues?q=is%3Aopen+is%3Aissue+user%3Ahapijs+label%3A%22new+contributor%22+`

- `See All` link for `Help Wanted` points to:

`https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Ahapijs+label%3A%22help+wanted%22` 
instead of 
`https://github.com/hapijs/hapi/issues?q=is%3Aopen+is%3Aissue+user%3Ahapijs+label%3A%22help+wanted%22`

**Comment by Marsup** [comment]
Those are not broken, it points at all the issues in the organization which is exactly what we want.

**Comment by karanjthakkar** [comment]
Ahh, my bad. I checked them in incognito. And it threw a 404.

On Mon, 13 Jun 2016 at 17:12, Nicolas Morel <notifications@github.com>
wrote:

> Those are not broken, it points at all the issues in the organization
> which is exactly what we want.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hapijs/hapijs.com/issues/398#issuecomment-225557989>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABvWKgnP_lz5cpru0eQMEJVG6Ew0bVFNks5qLUISgaJpZM4I0O8j>
> .
>
-- 

Regards,
Karan
Twitter/Instagram: @geekykaran

**Comment by Marsup** [comment]
Ha, didn't know github would protect that kind of query. I'm afraid there's nothing we can do.

**Comment by devinivy** [comment]
I verified that you just have to be signed-in– not necessarily part of the hapijs org.

**Comment by rdela** [comment]
@karanjthakkar lol this got me [all the way to a PR](https://github.com/hapijs/hapijs.com/pull/522) only to toss it without realizing this was the issue. A year later. Not sure this is a good idea after all @Marsup @devinivy as I gather it presupposes they are signed into GH?
