### ISSUE TITLE
crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest

### ISSUE THREAD

**Issue by rousos87** [hapijs/hapijs.com#410]
Hello

I am new on hapi and i need help.First of all i am using node version 6.3.0 and hapi version 13.5.0.Yesterday i tried to make a simple authentication system.But after i logged in i have this error: "internal/process/warning.js:24 (node:2661) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest".I tried to find a solution but nothing.Can anyone help me?

Thank you!

**Comment by hueniverse** [comment]
Please post this in https://github.com/hapijs/discuss
