### ISSUE TITLE
Testimonial - nicistore.com

### ISSUE THREAD

**Issue by andreftavares** [hapijs/hapijs.com#418]
**Company name**
- [NICI Store](https://nicistore.com) / [Yoonic Commerce](https://github.com/yoonic)

**Product name or use case**
- E-Commerce Backend API

**Is it in production or development?** 
- Production

**Contact information for further questions**
**Contact information for security alerts**
- @andreftavares / [andre@yoonic.net](mailto:andre@yoonic.net) / [@andreftavares](https://twitter.com/andreftavares)

**Link to logo if we can showcase your company on the new site**
- https://nicistore.com/static/logo.png

**User quote (with attribution) about your hapi user experience (up to 300 characters)**
I think that if you're writing a RESTful/API in Node.js you shouldn't look any further than Hapi.js. It's simple and lightweight, yet powerful and expandable as needed. I think it really solves the issue of removing the hassle of all the boilerplate needed when writing an API without being a bloated framework like many others!

**Comment by Marsup** [comment]
Fixed by #446.
