### ISSUE TITLE
http://hapijs.com/tutorials/auth?lang=en_US - “CL.exe” exited with code -1073741511, for 'npm install bcrypt --save"

### ISSUE THREAD

**Issue by RohitRane** [hapijs/hapijs.com#425]
0
down vote
favorite
I am going through the HAPI js tutorial Authentication section(http://hapijs.com/tutorials/auth?lang=en_US), which requires the "bcrypt". So I did "npm install bcrypt --save". But this is giving node-gyp errors like php was missing. So I followed the instructions given here : https://github.com/nodejs/node-gyp#installation

I even did :npm install --global --production windows-build-tools

But now it's throwing error :

"CL.exe" exited with code -1073741511

I have installed everything they asked for yet it's not allowing to install bcrypt. What do I do?

As simple tutorial exercise has taken me 2 days of research without any solution. Why use such dependency driven packages in your tutorial?

This is the actual console log I am getting on doing npm install bcrypt :

```
    m WARN package.json personal_assistant@1.0.0 No README data

bcrypt@0.8.7 install D:\learn\personal_assistant\server\node_modules\bcrypt
node-gyp rebuild


\learn\personal_assistant\server\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
ilding the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741511. [D:\learn\personal_
sistant\server\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
p ERR! build error
p ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
p ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
p ERR! stack     at emitTwo (events.js:87:13)
p ERR! stack     at ChildProcess.emit (events.js:172:7)
p ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
p ERR! System Windows_NT 6.1.7600
p ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
p ERR! cwd D:\learn\personal_assistant\server\node_modules\bcrypt
p ERR! node -v v4.5.0
p ERR! node-gyp -v v3.4.0
p ERR! not ok
m ERR! Windows_NT 6.1.7600
m ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"
m ERR! node v4.5.0
m ERR! npm  v2.15.9
m ERR! code ELIFECYCLE

m ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
m ERR! Exit status 1
m ERR!
m ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
m ERR! This is most likely a problem with the bcrypt package,
m ERR! not with npm itself.
m ERR! Tell the author that this fails on your system:
m ERR!     node-gyp rebuild
```

**Comment by AdriVanHoudt** [comment]
First of this is an issue with bcrypt not hapi so you should really open an issue there.
Second it appears [this](https://github.com/astro/node-expat/issues/57#issuecomment-21547903) has worked for some people

**Comment by AdriVanHoudt** [comment]
@RohitRane or anyone else reading this there is https://github.com/felixrieseberg/windows-build-tools now which should more easily solve native module stuff on windows 🎉

**Comment by zoe-1** [comment]
@RohitRane How much RAM do you have available on the system you are running?
FWIW,  bcrypt requires a lot of RAM.   So, if your system / VirtualBox / VMWare setup does not have 
enough RAM it will fail with various strange errors. Ran into this when trying to install bcrypt on a 
system with less the 2G of RAM.
