### ISSUE TITLE
Got hapi?

### ISSUE THREAD

**Issue by nlf** [hapijs/hapijs.com#43]
We are compiling a list of companies or products using hapi for a few reasons:
- **showcase logos** and user stories of successful hapi development for the new site
- create a private hapi **security notification list** for high risk alerts
- solicit **private feedback** about making hapi better
- potential hapi **developer event** in the coming months
- help companies to **hire** experienced hapi developers
- identify new hapi **core contributors** from other companies

What we need from you:
- Company name
- Product name or use case
- Is it in production or development?
- Contact information for further questions
- Contact information for security alerts
- Link to logo if we can showcase your company on the new site
- User quote (with attribution) about your hapi user experience (up to 300 characters)

Please add a PR with your company information here: https://github.com/hapijs/hapijs.com/blob/master/lib/community.js

**Comment by hueniverse** [comment]
Need to clone it and replace with text on the site telling people how to get added.
