### ISSUE TITLE
Site does not use HTTPS

### ISSUE THREAD

**Issue by jpwesselink** [hapijs/hapijs.com#434]
To protect content and users it would be better if hapijs.com would use HTTPS rather than HTTP.

**Comment by Marsup** [comment]
What exactly do you intend to protect with that ? It's a static site.

**Comment by AdriVanHoudt** [comment]
If anything it should redirect

**Comment by jpwesselink** [comment]
@Marsup HTTPS makes it harder to eavesdrop, change content and pose as someone else.

**Comment by jedireza** [comment]
I think what @Marsup meant was that there isn't any personal identifying information being passed around that needs to be encrypted. _The only cookie I observed from from Google Analytics._

I am curious about https being removed though. I have links to hapijs.com that used to work. Was https removed recently?

**Comment by jedireza** [comment]
👋

**Comment by patrickkettner** [comment]
while there is no personally identifiable pieces of information on the page, it is an API and links to code. A malicious third party could MITM and replace reputable links with false ones, prompting some users to install malware or serve viruses

**Comment by hueniverse** [comment]
Someone has to do the work and pay for the setup. I am not sure who that someone is.

**Comment by nlf** [comment]
that's me :) i'll take care of it sometime soon. i've been a bit busy or it would've already been done.

**Comment by AdriVanHoudt** [comment]
If you run it through cloudflare, the ssl is free. (as a reaction to `pay for the setup`)

**Comment by guahanweb** [comment]
Is there a reason not to just use a free cert from https://letsencrypt.org/? I don't have any insight into the hosting configuration you're using for the actual site, but aside from a little effort, I don't see why there would have to be any cost involved (unless you're binding to the VIP directly and doing SSL termination at that layer).

Let me know if there's anything I can do to help.

**Comment by nlf** [comment]
tada, https
