### ISSUE TITLE
Make "Lint" rules auto-fixable

### ISSUE THREAD

**Issue by iyobo** [hapijs/hapijs.com#452]
Hello team Hapi, great work!

Some of us are borderline OCD and enjoy focusing on the "wrong things" (EDIT: NOT an insult), but I think all the current linting rules need to be reduced to what can only be auto-fixed. Otherwise this just creates unneccessary busy-work that yields no actual benefit to anyone's code-base.

Rule violations like: 

- **hapi/hapi-scope-start - Missing blank line at beginning of function.** 
- **brace-style - Opening curly brace does not appear on the same line as controlling statement.**
- etc

do not seem to get fixed with `eslint --fix`.

**Comment by hueniverse** [comment]
You have zero chance of convincing me to make any rules looser. Feel free to try.
Also: https://gist.github.com/hueniverse/a06f6315ea736ed1b46d.

**Comment by iyobo** [comment]
Hi Eran :D, 
No insult meant. On second read-through, I can see how my initial comment could be seen as curt.

My point, however, is that if the rules exist, they should be made auto-fixable, no matter how opinionated they might be. This helps the community and every other part of the hapi ecosystem to easily and better stick with them for consistency.

Going through the linting code on github, there is currently no `autofix` boolean flag, neither are there any fix definitions per rule (see [http://eslint.org/docs/developer-guide/working-with-rules-new#applying-fixes](http://eslint.org/docs/developer-guide/working-with-rules-new#applying-fixes)).

**Comment by nlf** [comment]
pull requests to the eslint rules to add that ability would be welcome :)

see https://github.com/continuationlabs/eslint-plugin-hapi for where those can be found

**Comment by Xeoncross** [comment]
I fail to see how `hapi/hapi-scope-start` even made it into the styleguide without including an auto-fix option since every `format-on-save` or `ctrl+opt+f` toggle will cause you to have to manually go through the file and add newlines back to the function defs.

I assume everyone has this rule ` ...: 0` in their config or something.

**Comment by nlf** [comment]
this is completely the wrong place to make any of these arguments, not sure why i ever left this issue open in the first place
