### ISSUE TITLE
Broken alignment on community on larger screens

### ISSUE THREAD

**Issue by antony** [hapijs/hapijs.com#458]
This is most visible at 3200+, but I've spotted it at 1920 too.

Seems like some of the smaller logos end up appended to the previous quote under certain circumstances.

Tested on Chrome on Linux and Chrome on Mac. Screenshot is from Linux.

![broken alignment](https://cloud.githubusercontent.com/assets/218949/22291742/d24e1810-e2ff-11e6-9123-4e408f543eb5.png)

**Comment by johnbrett** [comment]
It's when the text is too short from the previous company quote. A min-height for the quote will fix this. This would be a great first PR for someone, happy to work with someone on it if they'd like :)

**Comment by devinivy** [comment]
But, what if there were a taller logo than TIDO's?  It just happens to be the tallest one right now.  The min-height might need to be supplemented by either 1. some more fancy styling work or 2. a policy around the aspect ratio of these logo images.

**Comment by AdriVanHoudt** [comment]
max-height on the logo and min-height on the quote?

**Comment by devinivy** [comment]
Yeah, if you wanna stretch the logo :D

**Comment by AdriVanHoudt** [comment]
stretch? if the logo is smaller than max-height it won't stretch?

**Comment by devinivy** [comment]
Right, but this TIDO one probably would be squashed, which they probably wouldn't love to see since it might be off brand.  Instead a `background-size: cover` should be able to "do the right thing" and scale the logo to fit inside a box– basically, by adding whitespace around the logo.

**Comment by AdriVanHoudt** [comment]
ah I was under the assumption max-height would also make it decently scale, but +1 on more reliable solutions

**Comment by swashcap** [comment]
Noticing this in a couple browsers @ 1280px wide:

![whoa-walmart](https://user-images.githubusercontent.com/1858316/27159250-7e06cc72-5120-11e7-9e5a-d6c9c8e1693e.jpg)

This due to the `cf` (clearfix) class’s `::after` pseudo element styling to make it those horizontal rules between `section.company`s.

Has anyone PR'd for this? If not, I’d be happy to fix it.

**Comment by antony** [comment]
@swashcap you should probably open that PR :)

**Comment by antony** [comment]
Works for me on 4k too. Closing this issue.
