### ISSUE TITLE
Sorting on API versions list is goofed up

### ISSUE THREAD

**Issue by jcollum** [hapijs/hapijs.com#469]
https://hapijs.com/api

There's some screwiness on that page in the sorting of the list of versions. I'm trying to upload an image of it but getting a 403 on github's upload. Anyway, the versions aren't sorted right, it goes 14.1.0 then 13.5.3 then 14.0.0 then 13.5.0

Also 13.5.3 is returning a 404

**Comment by nlf** [comment]
the 404 makes sense, seeing as there is no 13.5.3 tag in github. why it's there at all right now, i'm not sure. i don't know when that tag was removed, but i believe that method was only supposed to be getting cached for 15 minutes.

the releases are sorted right now in order of when they were released, which i agree is silly, however. they should be sorted by semver.

**Comment by mtharrison** [comment]
The versions are coming from npm (`npm.versions()`), not Github. The 13.5.3 release is still on npm so that's why it's still present on the site.

**Comment by nlf** [comment]
well there you go, mystery solved. we should change that to use github instead.

**Comment by mtharrison** [comment]
I guess we'll change it anyway, but I made a PR to fix the sorting: https://github.com/hapijs/hapijs.com/pull/470

**Comment by JustinBeaudry** [comment]
Still seeing this as an issue so #470 didn't quite solve the issue completely:

<img width="232" alt="screen shot 2018-04-16 at 1 50 53 pm" src="https://user-images.githubusercontent.com/686771/38834419-49cc3cd2-417d-11e8-8129-fc597e194d18.png">

<img width="232" alt="screen shot 2018-04-16 at 1 50 38 pm" src="https://user-images.githubusercontent.com/686771/38834420-4d3d0914-417d-11e8-809f-b39fa3c419b0.png">

**Comment by hueniverse** [comment]
Not needed once #584
