### ISSUE TITLE
SSL Certificate expired for hapijs.com

### ISSUE THREAD

**Issue by franksrevenge** [hapijs/hapijs.com#476]
The website is currently responding with an expired SSL certificate.

> hapijs.com uses an invalid security certificate
> 
> The certificate expired on Monday, March 6, 2017 1:52 PM. The current time is Monday, March 6, 2017 2:08 PM.
> 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by AdriVanHoudt** [comment]
cc @nlf

**Comment by sirgallifrey** [comment]
Thanks for reporting @franksrevenge

**Comment by nlf** [comment]
whoops. fixed, thanks for letting me know!
