### ISSUE TITLE
Add patreon to the landing page

### ISSUE THREAD

**Issue by pkaske** [hapijs/hapijs.com#492]
Recently @hueniverse made me aware on twitter that I can support hapi on patreon.
I wasn't able to find this information on hapi's website and I think that hurts the whole opportunity to raise funds.

Or how your president would likely tweet:
"Hapijs, Great project! Great community. Bad marketing. Bad!"

Huge thanks to everybody in this community who enables small devs like me to build great stuff.

**Comment by devinivy** [comment]
I think this is a great idea :) I can imagine it on the homepage near all the logos of companies that benefit from hapi, and on the contribute page.

**Comment by pkaske** [comment]
The thing with "contribute $100 and get added to the security email list" could also be mentioned IMO

**Comment by Marsup** [comment]
I'm not against but just so things are clear, you'd be supporting Eran (which probably spends 99.9% of that money on hapi), not hapi itself.

**Comment by hueniverse** [comment]
We should take a more consistent and generic approach to this. We should have a sponsors page where each module can have a little section listing sponsors and how to support that module. My Patreon page supports me and no one else, and if it is mentioned on the hapijs.com site, that needs to be clear as I don't want to create the false impression supporting my work is a generic support for the project.
