### ISSUE TITLE
site is down?

### ISSUE THREAD

**Issue by g-k** [hapijs/hapijs.com#507]
Looks like the site is down http://downforeveryoneorjustme.com/hapijs.com

![image](https://user-images.githubusercontent.com/226605/29985583-915a343a-8f2d-11e7-8a53-b9ee452a683b.png)

**Comment by nlf** [comment]
sure is, looking into it now

**Comment by nlf** [comment]
fixed it

**Comment by dhaneesh-r** [comment]
Looks like the hapijs.com is down

http://downforeveryoneorjustme.com/hapijs.com

![down](https://user-images.githubusercontent.com/1210161/31654667-49d7fa08-b344-11e7-8269-3b5170768882.PNG)
