### ISSUE TITLE
hapijs.com/api nav and link anchors are not consistent/stable

### ISSUE THREAD

**Issue by csrl** [hapijs/hapijs.com#527]
When following the right hand nav menu, eg. for `server.dependency(dependencies, [after])`, the url fragment shows as `#server.dependency()`, but navigating directly to https://hapijs.com/api#server.dependency() is not valid.  This holds true for other nav menu entries as well.

However, clicking on that section's link icon, results in the fragment `#-serverdependencydependencies-after` which does work as a direct link of https://hapijs.com/api#-serverdependencydependencies-after

But, that working link has also recently changed, by having a '-' prepended, breaking external documentation links, such as in hapijs/glue#108  The previous fragment was `#serverdependencydependencies-after`, not having the leading '-'.

It would be useful if the nav menu link was the same as the anchor link, and the structure of the fragment didn't change unless the api itself changed.

edit: corrected reference example

**Comment by JustinBeaudry** [comment]
@csrl I've noted this from a change I made recently to https://github.com/hapijs/hapi API.md. Seems to me like theres a larger issue with how those fragments are generated.

**Comment by hueniverse** [comment]
It might be a problem with how the page is loaded. If you open the https://hapijs.com/api#server.dependency() link it doesn't go to the right place, but if you then click on another navigation link and hit back, it does go to the right place...

**Comment by nlf** [comment]
It’s a race condition, the browser is trying to jump to an anchor that hasn’t been rendered yet

**Comment by hueniverse** [comment]
Can we add a refresh somehow?

**Comment by nlf** [comment]
I think we can add some code to manually jump to the correct anchor when the document is ready

**Comment by csrl** [comment]
It seems this wasn't fixed?  Is it closed because it won't be fixed?

**Comment by hueniverse** [comment]
Closed because no one was working on it and after a year I decided to close it and let someone reopen if they feel strongly about it. I'll let @Nargonath decide what he wants to do with it.

**Comment by Nargonath** [comment]
Regarding the latest discussions about revamping the website on Slack, this issue will most likely disappear so I'm going to close it for now. If the revamp doesn't go forward, I'll reopen it.
