### ISSUE TITLE
Upgrading stylus to the latest version

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapijs.com#559]
I'm on Windows 10 with `npm@5.6` and `node@8.9.4` and I get an error while trying to `make` the project:
![image](https://user-images.githubusercontent.com/583657/37053991-f4821220-217d-11e8-9a49-b3841e8f2896.png)

If I update `stylus` to version `0.54.5` from `0.52.4` it solves the problem. I don't know what side effect it could have but we could update the version in the `package.json`. If that's ok I can submit a PR for it.

**Comment by AdriVanHoudt** [comment]
Seems like https://github.com/stylus/stylus/blob/dev/History.md#0530--2015-12-14 0.53.0 had a path fix for windows 👌

**Comment by Nargonath** [comment]
@AdriVanHoudt Indeed. Thanks. I was a bit lazy to check the patch log. Should we upgrade only to this version or shall we consider upgrading to the latest?

**Comment by AdriVanHoudt** [comment]
I have no knowledge of stylus or how it is used by this repo but if possible go to the latest version, I don't remember seeing breaking changes in the log

**Comment by Nargonath** [comment]
There wasn't any breaking changes in the patch log and I installed the dep on local and could start the website. I did not notice any error on my side.

**Comment by Nargonath** [comment]
Master is already up to date with the stylus version. I just forgot to update my fork from the main repo.
