### ISSUE TITLE
Hapi 17 documentation shown in all cases

### ISSUE THREAD

**Issue by Marsup** [hapijs/hapijs.com#562]
No matter which version I pick on the website, I always get the hapi 17 one.

I don't know yet if it's a cache issue or something else.

**Comment by mtharrison** [comment]
Looks like the cache key is just `github.reference`. It should have the version/tag as part of the cache key.

**Comment by mtharrison** [comment]
https://github.com/hapijs/hapijs.com/pull/564/files
