### ISSUE TITLE
Use tag interpolation for whitespace control

### ISSUE THREAD

**Issue by allybee** [hapijs/hapijs.com#573]
By default, [Pug removes all spaces before and after tags](https://pugjs.org/language/interpolation.html#whitespace-control). Because of this, the inline html tags are running together. I noticed this specifically on the homepage:

<img width="688" alt="screen shot 2018-03-13 at 12 39 29 pm" src="https://user-images.githubusercontent.com/1250930/37359478-b0fa52b8-26bb-11e8-85de-69b3e1415806.png">

This can be solved with Pug's tag interpolation. e.g., by replacing this:

```pug
p Launch the application by running
  code npm start
  |  and open
  em localhost:8000/hello
  |  in your browser.
```

with this:

```pug
p Launch the application by running #[code npm start] and open #[em localhost:8000/hello] in your browser.
```

or even just using inline HTML:

```html
p Launch the application by running <code>npm start</code> and open <em>localhost:8000/hello</em> in your browser.
```

I also find this makes the code a bit more readable. 

I am happy to create a pull request to fix this if you'd like.

**Comment by devinivy** [comment]
Thanks for the great writeup/explanation!  We'd definitely take a PR :)
