### ISSUE TITLE
Move "Getting started" to the top

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapijs.com#582]
It's a bit absurd right now...

![image](https://user-images.githubusercontent.com/56631/39086355-f797a30e-4544-11e8-8036-a5ead1dcaa52.png)

**Comment by ErickWendel** [comment]
I'm trying to fix, but the project isn't working. So, I remove "token" word from  internals.requestOptions.headers.authorization in GitHub.js file and now It works. 

Only `/tutorials is` with `Response Error: 401 Unauthorized` error when I access, another routes is running ok, but I don't know what only this route is not working

**Comment by ErickWendel** [comment]
that issue was merged :D Can you close this issue ?
