### ISSUE TITLE
Incomplete documentation /api#-serverrulesprocessor-options

### ISSUE THREAD

**Issue by Rob-pw** [hapijs/hapijs.com#603]
The descriptor associated with the `rules` parameter under `processor - a function using the signature function(rules, info) where:` appears to be missing.

https://hapijs.com/api#-serverrulesprocessor-options

**Comment by AdriVanHoudt** [comment]
I would suggest looking at the hapi code and do a PR with the missing info.
If you need pointers or anything let us know!

**Comment by Nargonath** [comment]
@rob-h-w Are you working on the PR?
