### ISSUE TITLE
Some of the companies featured on hapijs.com no longer exist

### ISSUE THREAD

**Issue by shadone** [hapijs/hapijs.com#604]
Hi there,

I've noticed that 4 out of 12 companies featured on the main page hapijs.com no longer exist:

- https://octovis.com
- https://nicistore.com/
- http://pebblecode.com/
- https://feedient.com/

Those should probably be removed

<img width="1261" alt="screen shot 2018-08-17 at 15 03 47" src="https://user-images.githubusercontent.com/25523/44267545-f5277800-a22e-11e8-9cf5-2df25baa510c.png">

**Comment by AdriVanHoudt** [comment]
For Feedient we could point to https://github.com/Feedient/Server

**Comment by Nargonath** [comment]
I worked on it. I finished writing the code. I just need to test it before I make a PR.
