### ISSUE TITLE
hapijs.com is down?

### ISSUE THREAD

**Issue by Mattrachwal** [hapijs/hapijs.com#607]
Im trying to access hapijs.com but it appears to be down, Im browsing from a different country than I normally do but I don't think I there are any blocks that I'm unaware of.

I used a few online tools to verify and I believe its down and not just my network configuration.

**Comment by devinivy** [comment]
In the interim I have stood up the site on glitch: https://hapijs-com.glitch.me/

**Comment by nlf** [comment]
it's back up
