### ISSUE TITLE
Update code samples to use route.options instead of route.config

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapijs.com#608]
In the [`route.options.pre`](https://hapijs.com/api#route.options.pre) section of the website, the code sample still show the `route.config` object which is IIRC the < v17 way of doing things and has now been deprecated in favor of `route.options`. I'd suggest just using `options` instead of `config`.

I'll be happy to make the easy PR for it, but I wanted to ask prior to make sure I'm not wrong. 😃 
Thanks.

**Comment by devinivy** [comment]
Sounds right to me 👌It seems like almost all of the docs use `config` rather than `options`!

**Comment by Nargonath** [comment]
Then I could change the issue and make it about updating all the code samples instead.

![update all the things](https://memegenerator.net/img/instances/66279455/update-all-the-things.jpg)
