### ISSUE TITLE
Add prettier to the project

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapijs.com#609]
Would be cool to add `prettier` configuration to the project either as `.prettierrc` or in the `package.json`. This way `prettier` user would not break code format when contributing.

Bonus: Add a `precommit` hook to format code in the commit to make sure the format stay the same even for contributors that do not use prettier in their IDE. We would need to update travis configuration as well to run the formatting as well so even people committing from Github interface would not be able to bypass the formatting process.

I'd be happy to make a PR for that if you're ok with it.

**Comment by codeShaurya** [comment]
What will be the rules ??
Can I make new rules for this project? ?

**Comment by Marsup** [comment]
I see no reason to change for prettier, we already have the linter doing its job.

**Comment by Nargonath** [comment]
I intended this issue more as a discussion in the first place to see if that's would be something people would accept to add in the project. My reasoning behind it was that lots of people now are using Prettier to autoformat their code through their IDE (including myself) and usually it modifies the current code base format (adding leading comma, line length and such) hence you have to deactivate it while working on the project which you sometimes forget to do. Adding prettier would guarantee we won't end up with different code format in PR (perhaps that's a non-existing problem) but I thought it would be nice to ease contributions.

IMHO linters and prettier can work hand-in-hand as they don't address the same problem the former works on code syntax while the latter is about code format.

**Comment by Marsup** [comment]
Your IDE is kind of your problem :) Can't your IDE remember that setting ?

Tests (aka CI) already run the linting, there's a command to automatically fix it as well. I don't see a compelling argument to replace that.

Also, considering the very limited set of options prettier has, good luck making it compatible with hapi's style guide.

**Comment by Nargonath** [comment]
Yeah I can definitely set that setting. 

Indeed doesn't seem like it would provide any value. I'll just close this issue.

**Comment by Marsup** [comment]
> Yeah I can definitely set that setting.

You think prettier can follow our rules ?

**Comment by Nargonath** [comment]
IIRC the project uses `eslint`. `prettier` and `eslint` are not mutually exclusive. We can use [`prettier-eslint`](https://github.com/prettier/prettier-eslint) which would allow us to leverage `prettier` advantages (format file format other than JS) and also follow the hapi styleguide for the JS. We would just need to disable the `eslint` rules that conflict with `prettier` settings such as: `semi`, `comma-dangle` and such.
