### ISSUE TITLE
Create error handling tutorial

### ISSUE THREAD

**Issue by KyleAMathews** [hapijs/hapijs.com#62]
This is a big plus to using Hapi.js but the information on how to use Hapi.error etc. seems a bit scattered atm.

**Comment by nelsonic** [comment]
@KyleAMathews did you ever figure this out? 
I _ask_ because we were trying to figure out how to do error handling the "right" way in Hapi but weren't able to find API docs or a tutorial ... 😞

**Comment by devinivy** [comment]
@nelsonic you might find this section of the docs interesting https://github.com/hapijs/hapi/blob/master/API.md#error-transformation

**Comment by nelsonic** [comment]
@devinivy, yeah, the API docs for **Error response** and **Error transformation** are _good_ (_we used them when deriving our `preResponse` plugin_) but we were searching for more of an **Error _Handling_** Guide i.e. what are the "Best Practices" in Hapi Web Apps? _preferably_ with a "real world" example ...
