### ISSUE TITLE
rename or remove host:'localhost'

### ISSUE THREAD

**Issue by dasDaniel** [hapijs/hapijs.com#629]
the tutorial  `/lib/tutorials/en_US/getting-started.md` specifies the server to use `host: 'localhost'`

While I see that this was added in https://github.com/hapijs/hapijs.com/pull/427 there is a drawback to this, which should be considered.

When using `localhost` in a docker environment, this creates an issue, where the server is only available internally to the container. For containers that don't include nginx or some other internal way to bind/map the port, the server is unreachable.

**Comment by hueniverse** [comment]
localhost is the most secure setting. We can add a note about it, but the default should always be localhost.

**Comment by Nargonath** [comment]
@dasDaniel Are you planning on making a PR for this note?

**Comment by dasDaniel** [comment]
@hueniverse  
 
> localhost is the most secure setting. We can add a note about it, but the default should always be localhost.

If that's the case, why wouldn't that be the default ?

> server.options.address
> Default value: '0.0.0.0' (all available network interfaces).


@Nargonath  Can do

**Comment by Nargonath** [comment]
@dasDaniel Alright, let's see where this discussion goes and I might reopen it if you or anyone else decide to land a PR for it.

**Comment by hueniverse** [comment]
It's not the internal default for historical reasons. It is common practice to use localhost in examples.
