### ISSUE TITLE
hapijs.com/security

### ISSUE THREAD

**Issue by adambrault** [hapijs/hapijs.com#64]
@hueniverse I know you care like crazy about security and must already have a process for this. If I can help, I'd be happy to.

**Comment by JustinBeaudry** [comment]
What would be the ideal security policy? @hueniverse Do you just want emails coming to you or would you prefer a portal (e.g. link) to https://github.com/hapijs/hapi/issues with a Security tag?

**Comment by hueniverse** [comment]
I need to write a security policy and then someone can turn that into a new page.

**Comment by Nargonath** [comment]
@hueniverse Where are we on this? Do you have a security policy you're happy with?

**Comment by hueniverse** [comment]
It's on my list. Hopefully in March.

**Comment by Nargonath** [comment]
@hueniverse Alright, nice. 👍
