### ISSUE TITLE
Remove Gitter/IRC mentions in GETTING_STARTED other than english 

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapijs.com#641]
I cannot do it by myself as I cannot read/write ~Portugese~, Korean, ~Turkish~ and ~Chinese~.

**Comment by fguler** [comment]
I have send a PR regarding the Turkish version.

**Comment by AdriVanHoudt** [comment]
you are all amazing, thank you ✨

**Comment by hueniverse** [comment]
@L42y can you add the slack link?

**Comment by L42y** [comment]
@hueniverse sure thing

**Comment by L42y** [comment]
@hueniverse the Slack link in GETTING_STARTED Chinese is the same as in other languages, so I assume it's updated?

**Comment by hueniverse** [comment]
@L42y Thanks. I only saw a deletion in your PR so I wanted to be sure the link was there.
