### ISSUE TITLE
The "Getting started" script should follow coding conventions

### ISSUE THREAD

**Issue by Getz85** [hapijs/hapijs.com#642]
I begin to learn hapi, and I just tried the "Getting started" script on the homepage of hapijs.com.

But the start function doesn't follow the [Function Declaration Coding Conventions](https://hapijs.com/styleguide#function-declaration):

```javascript
// Start the server
async function start() {

    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log('Server running at:', server.info.uri);
};
```

must be 

```javascript
// Start the server
const start = async function () {

    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log('Server running at:', server.info.uri);
};
```

**Comment by Nargonath** [comment]
Yes indeed, good catch @Getz85 . Do you want to setup a PR to update it? 😃

**Comment by Getz85** [comment]
@Nargonath  I'd loved too, but I can't start the app (because of this: https://github.com/hapijs/hapijs.com/issues/597 ). I tried on Windows and Docker: same error.

**Comment by Nargonath** [comment]
@Getz85 Damn. Which version of Windows are you using? Do you use it through Windows SubLinux System?

You can still use the Edit button on the header at the top of the page and open the PR through Github's interface (cf. below):
![image](https://user-images.githubusercontent.com/583657/50350577-dcfa9900-053f-11e9-9096-418f9ec0870a.png)

**Comment by Getz85** [comment]
I'm not very confortable with doing a pull request without testing it, but it's done :)

I'm on Windows 10 Home 64 bits, I tried in Cmder and in the basic cmd shell.

**Comment by Nargonath** [comment]
Thanks @Getz85. Don't worry about that, if I know in advance I'll just test it myself and make any comments if needed.
