### ISSUE TITLE
Homepage was 500ing

### ISSUE THREAD

**Issue by devinivy** [hapijs/hapijs.com#652]
The live homepage currently shows a templated 500 page with the message,
> Cannot read property 'filter' of null

I cannot reproduce locally using a bad github key, which was my initial hunch.

**Comment by devinivy** [comment]
Oddly enough this seems to have fixed itself.  I'm going to leave this open in case someone wants to try and figure out what happened.

**Comment by gunar** [comment]
Tis fixed

**Comment by devinivy** [comment]
I know!  I was pretty stumped.  I tried running the site locally under some bad conditions, e.g. no connectivity, no github token, bad github token.  I couldn't get the same behavior.  I did, however, find this in `Utils.download()`: https://github.com/hapijs/hapijs.com/blob/5c586ef44aea69bc9656ab5c9f0b59c630013565/lib/utils.js#L20-L23.  I would put my money on that, but would have to peek the logs to know.

**Comment by Nargonath** [comment]
Could be it, indeed.

**Comment by Nargonath** [comment]
@devinivy have you experienced this bug again?

**Comment by Nargonath** [comment]
closing for now @devinivy, feel free to reopen if it happens again

**Comment by erevecov** [comment]
Same issue today.

**Comment by Nargonath** [comment]
Yeah I noticed it yesterday also. There is an ongoing PR to fix it. I haven't finished it yet. I hope to find the time to get it done soon (hopefully this weekend 🤞 )
