### ISSUE TITLE
Call for plugins

### ISSUE THREAD

**Issue by nlf** [hapijs/hapijs.com#7]
We've added a [plugin list](http://hapijs.com/plugins) to hapijs.com!

We need your help though. If you wrote a plugin, or have a plugin that you use often that isn't already listed, please send us a [pull request](https://github.com/hapijs/hapijs.com/blob/beta/lib/plugins.js) adding it to the site.

If your plugin fits under one of the existing categories, please use it. If not, creating a new category is fine. Let's keep the list in alphabetical order to be fair to everyone and get this thing filled out!

**Comment by arb** [comment]
Think we can close this guy up now?

**Comment by nlf** [comment]
I was planning to keep it open, though I suppose we can also just add this information to the README and close the issue. Likewise for #43
