### ISSUE TITLE
Current version on homepage is out of date

### ISSUE THREAD

**Issue by yonjah** [hapijs/hapijs.com#713]
https://hapijs.com/ is currently showing - 

> Current version: 18.1.0 ● Latest update: 12 days ago ● Downloads last month: 1,017,620

even though v18.3.1 is available 
I assume it still pulls the data from npm `hapi` and not `@hapi/hapi`

**Comment by Nargonath** [comment]
Hum that's a very good remark! Thank you. Do you want to make a PR for it?

**Comment by yonjah** [comment]
Sure I assume it's just a simple change to `lib/npm.js`

Only thing is about downloads count. Do we wont to add both counts from `hapi` and `@hapi/hapi`
I assume if I'll only get `@hapi/hapi` downloads they will be extremely low at the moment
