### ISSUE TITLE
Evaluating Hapi for use at Jibo

### ISSUE THREAD

**Issue by richsad** [hapijs/hapijs.com#85]
Hi, My name is Rich Sadowsky. I am responding to your request that we provide usage info by opening an issue here. I'm Chief Architect Cloud at Jibo, Inc., makers of the world's first family robot. I want to be clear that I am still evaluating Hapi and have not officially started development with it. But my instincts tell me this is the right framework. I am eager to evaluate 8.0 but currently npm is giving me 7.5.2. I'll check 8 out from here for the next phase of my eval.

Company name: Jibo, Inc.

Product name or use case: Jibo is the name of the company and the product. It's a social robot. It makes use of many services in the cloud. As Chief Architect Cloud, I am in charge of selecting technologies for the cloud components of the infrastructure.

Is it in production or development? Hapi is still under evaluation but is the leading candidate for a framework. Therefore we are still in development.

Contact information for further questions: rich@myjibo.com or rich@jibo.org

Contact information for security alerts: rich@jibo.org

Link to logo if we can showcase your company on the new site: our corporate website is at http://www,myjibo.com. Please do not include the logo yet. 

User quote (with attribution) about your hapi user experience (up to 300 characters)
I decided to evaluate hapi after reading about it and seeing the corporate logos of the other users. We are expecting Jibo to be a massive success and want to build a system that will scale quickly. I've used Express and Restify in prior projects. At the beginning of each new project I research what is available and select the best product.

^^^^ I will have a better quote once I start development.

**Comment by nlf** [comment]
Rich,

I went ahead and added your information. Let us know when we can include your logo, and also if you'd like to change your quote later. Thanks!
